language: node_js
node_js:
    - v15.12.0

script:
  - npm install
  - npm test
  - npm run build

deploy:
  provider: surge
  skip_cleanup: true
  domain: awesome-crown.surge.sh
  project: ./build/

on:
 branch: master